In [ ]:
# Лабораторная работа ВВИТ №3: Освоение многомерных массивов и математических операций с NumPy

In [ ]:
# Задание 1:

In [20]:
import pandas as pd # Импортируем библиотеки.
import numpy as np
train = pd.read_csv('train.csv') 

In [30]:
survive = (train['Survived']).to_numpy() # Создаём массив numpy с данными о выживших. 
survive

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [29]:
overall_survive = sum(survive) # Общее количество выживших. 
overall_survive

342

In [ ]:
# Задание 2: 

In [31]:
passenger_info = train[['Age', 'Fare']].to_numpy() # Двумерный массив с данными о возрасте и стоимости билета. 
passenger_info

array([[22.    ,  7.25  ],
       [38.    , 71.2833],
       [26.    ,  7.925 ],
       ...,
       [    nan, 23.45  ],
       [26.    , 30.    ],
       [32.    ,  7.75  ]])

In [32]:
truepassenger_info = passenger_info[passenger_info[:, 0].argsort()] # Отсортированный массив по возрасту пассажиров. 
truepassenger_info

array([[  0.42  ,   8.5167],
       [  0.67  ,  14.5   ],
       [  0.75  ,  19.2583],
       ...,
       [     nan,  13.8625],
       [     nan,   7.75  ],
       [     nan, 227.525 ]])

In [34]:
youngest_passenger = train.loc[train['Age'].idxmin()] # Вывод информации о самом старшем и самом младшем пассажире.
oldest_passenger = train.loc[train['Age'].idxmax()]

In [35]:
youngest_passenger # Самый младший.

PassengerId                                804
Survived                                     1
Pclass                                       3
Name           Thomas, Master. Assad Alexander
Sex                                       male
Age                                       0.42
SibSp                                        0
Parch                                        1
Ticket                                    2625
Fare                                    8.5167
Cabin                                      NaN
Embarked                                     C
Name: 803, dtype: object

In [36]:
oldest_passenger # Самый старший.

PassengerId                                     631
Survived                                          1
Pclass                                            1
Name           Barkworth, Mr. Algernon Henry Wilson
Sex                                            male
Age                                            80.0
SibSp                                             0
Parch                                             0
Ticket                                        27042
Fare                                           30.0
Cabin                                           A23
Embarked                                          S
Name: 630, dtype: object

In [ ]:
# Задание 3: 

In [37]:
family_info = train[['SibSp', 'Parch']].to_numpy() # Массив о количестве родственников у пассажиров. 
family_info

array([[1, 0],
       [1, 0],
       [0, 0],
       ...,
       [1, 2],
       [0, 0],
       [0, 0]], dtype=int64)

In [38]:
total_relatives = np.sum(family_info) # Считаем общее количество родственников
total_relatives

806

In [40]:
max_relatives_index = np.argmax(np.sum(family_info, axis=1)) # Наибольшее количество родственников. 
passenger_max_relatives = train.loc[max_relatives_index]
passenger_max_relatives

PassengerId                           160
Survived                                0
Pclass                                  3
Name           Sage, Master. Thomas Henry
Sex                                  male
Age                                   NaN
SibSp                                   8
Parch                                   2
Ticket                           CA. 2343
Fare                                69.55
Cabin                                 NaN
Embarked                                S
Name: 159, dtype: object